version: "3.3"

networks:
  stack_ponte:
    external: true

services:
  db:
    image: mariadb
    restart: always
    container_name: ${DATABASE}
    user: 1000:100
    environment:
      MARIADB_ROOT_PASSWORD: ${DBPASS}
      MARIADB_DATABASE: ${DATABASE}
    volumes:
      - ${VOLUMES}/maria:/var/lib/mysql
    networks:
      - stack_ponte
    ports:
      - 3306:8080

  traefik:
    image: traefik:v2.8.0
    restart: always
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stack_ponte
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  #  duplicati:
  #    image: lscr.io/linuxserver/duplicati:latest
  #    container_name: duplicati
  #    environment:
  #      - PUID=1000
  #      - PGID=1000
  #      - TZ=${TZ}
  #      - CLI_ARGS= #optional
  #    volumes:
  #      - ${VOLUMES}/duplicati:/config
  #      - /mnt/wolf/files/Developer/backups:/back
  #      - /mnt/wolf/files/Developer:/data
  #    ports:
  #      - 8200:8200
  #    restart: unless-stopped
  #    networks:
  #      - stack_ponte
  #    labels:
  #      - "traefik.enable=true"
  #      - traefik.http.routers.duplicati.rule=Host(`duplicati.${DOMAIN}`)
  #      - traefik.http.services.duplicati.loadbalancer.server.port=8200


  phpmyadmin:
    image: linuxserver/phpmyadmin:5.2.0
    container_name: phpmyadmin
    restart: always
    ports:
      - 2050:80
    networks:
      - stack_ponte
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PMA_ARBITRARY=1

    labels:
      - "traefik.enable=true"
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN}`)
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
