version: '3'

networks:
  internal:
    driver: bridge

services:
  backend:
    container_name: 'back_monolito'
    image: 'node:lts-alpine'
    working_dir: /app
    volumes:
      - '../:/app'
    networks:
      - internal
    command: 'npm run ts'
    ports:
      - 4444:4333
      - 9229:9229
      - 7001:7001
    labels:
      - 'traefik.enable=true'
      - traefik.http.routers.monolito.rule=Host(`monolito.localhost`)
      - traefik.http.services.monolito.loadbalancer.server.port=4333
