
version: "2"

networks:
  internal:
    driver: bridge

services:
  cloudflare-ddns:
      image: oznu/cloudflare-ddns:latest                 # use 'latest' para linux ou 'armhf' or 'aarch64' se usar um Raspberry Pi
      restart: always
      networks:
        - internal
      environment:
        - API_KEY=${APICLOUNDFLARE}     # coloque sua chave de api da cloudflare
        - ZONE=${HOST}                     # coloque o seu dominio                             
        - PROXIED=true

  mysql:
    container_name: mysql_${HOST}
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      # MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${USER}
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_PASSWORD: ${PASS}
      SERVICE_NAME: mysql.${HOST}
    volumes:
      - ../database/mysql:/var/lib/mysql
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.mysql.rule=Host(`mysql.${DOMAIN}`)
      - traefik.http.services.mysql.loadbalancer.server.port=3306

  phpmyadmin:
    container_name: "phpmyadminserver"
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql_${HOST}
    depends_on:
      - mysql
    ports:
      - 2052:80
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN}`)
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:2095"
      - "--entrypoints.websecure.address=:2096"
    ports:
      - "2095:2095"
      - "8880:8080"
      - "2096:2096"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
